# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_cumsum2d <- function(indat, threshold, comparator = "ge", includeLow = TRUE, includeHigh = TRUE) {
    .Call(`_harpCore_cpp_cumsum2d`, indat, threshold, comparator, includeLow, includeHigh)
}

cpp_nbhd_smooth_cumsum <- function(indat, rad, boundaryCondition = "zero_pad") {
    .Call(`_harpCore_cpp_nbhd_smooth_cumsum`, indat, rad, boundaryCondition)
}

cpp_nbhd_smooth <- function(x, rad, threshold, comparator = "ge", includeLow = TRUE, includeHigh = TRUE, boundaryCondition = "zero_pad") {
    .Call(`_harpCore_cpp_nbhd_smooth`, x, rad, threshold, comparator, includeLow, includeHigh, boundaryCondition)
}

