# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_cumsum2d <- function(indat, threshold, comparator = "ge", includeLow = TRUE, includeHigh = TRUE) {
    .Call(`_harpCore_cpp_cumsum2d`, indat, threshold, comparator, includeLow, includeHigh)
}

cpp_nbhd_smooth_cumsum <- function(indat, rad, boundaryCondition = "zero_pad") {
    .Call(`_harpCore_cpp_nbhd_smooth_cumsum`, indat, rad, boundaryCondition)
}

cpp_nbhd_smooth <- function(indat, rad, threshold, comparator = "ge", includeLow = TRUE, includeHigh = TRUE, boundaryCondition = "zero_pad") {
    .Call(`_harpCore_cpp_nbhd_smooth`, indat, rad, threshold, comparator, includeLow, includeHigh, boundaryCondition)
}

cpp_geolist_mean <- function(geolist, na_rm = FALSE) {
    .Call(`_harpCore_cpp_geolist_mean`, geolist, na_rm)
}

cpp_geolist_sum <- function(geolist, na_rm = FALSE) {
    .Call(`_harpCore_cpp_geolist_sum`, geolist, na_rm)
}

cpp_geolist_prod <- function(geolist, na_rm = FALSE) {
    .Call(`_harpCore_cpp_geolist_prod`, geolist, na_rm)
}

cpp_geolist_min <- function(geolist, na_rm = FALSE) {
    .Call(`_harpCore_cpp_geolist_min`, geolist, na_rm)
}

cpp_geolist_max <- function(geolist, na_rm = FALSE) {
    .Call(`_harpCore_cpp_geolist_max`, geolist, na_rm)
}

cpp_geolist_var_sd <- function(geolist, na_rm = FALSE, var = TRUE) {
    .Call(`_harpCore_cpp_geolist_var_sd`, geolist, na_rm, var)
}

